//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employes
    {
        public int idfuncionario { get; set; }
        public string nome { get; set; }
        public Nullable<int> telefone { get; set; }
        public Nullable<int> rg { get; set; }
        public string endereço { get; set; }
        public Nullable<float> salario { get; set; }
        public decimal? valorHoraExtra { get; set; }
    }
}
